### ISSUE TITLE
Port to USB HID

### ISSUE THREAD

**Issue by mangemayur** [Hamberthm/esp32-bt2ps2#4]
This is not an issue. 
but can this code ported to use Bluetooth(Classic) Keyboard to pair with ESP32 board - that act as USB HID Device (keyboard).
I know its possible - but not in micropython/circuitpython... it has be written in C (and i learned C almost 24 years back in my collage days ... so my C skills are completely rusted) 

My bad - adding this to Discussion and not issue

**Comment by Hamberthm** [comment]
Hi there! This project is composed of two parts; one is the PS2 emulator side ([esp32-ps2dev.cpp](https://github.com/Hamberthm/esp32-bt2ps2/blob/main/main/esp32-ps2dev.cpp)) and the other is the Bluetooth side of things [bt_keyboard.cpp](https://github.com/Hamberthm/esp32-bt2ps2/blob/main/main/bt_keyboard.cpp). In the middle is the glue code (BT HID to PS2 code parser), Typematic emulation and so on ([main.cpp](https://github.com/Hamberthm/esp32-bt2ps2/blob/main/main/main.cpp)). 
What you want to do is to replace the PS2 emulator for a USB HID interface, then you won't need to parse the HID codes coming from the Bluetooth side and simply send them to a USB HID Keyboard emulator. I guess there's plenty of USB HID code out there for the ESP32, in wouldn't be too hard to replace the PS2 code for that. 
Currently I'm totally overwhelmed by my obligations so I'm not able to help you on this, but take this as a heads-up and let's leave this open for a while to see if somebody can help you besides me.

Cheers and good luck!
Humberto

**Comment by mangemayur** [comment]
Just one more question - can you check whether your current setup works in Bios - means -> when machine boots, can you presess F2/F12/Del key to enter into bios and make certain changes using your current ESP32 change

The reason i am asking is .. i tried doing this using RaspberryPi Zero -> it workes smoothly Bluetooth HID USB Proxy -> but only in windows .. not at bios level 
one of the major issue i am facing currently is my employer has bitlocker encrypted drive and hence i need to supply the password before machine boots into windows

**Comment by Hamberthm** [comment]
Sorry for the delay on respoding, I was on vacation!. Yes, on mi 486 PC with AMIBIOS I can press DEL to enter BIOS setup just as a regular keyboard does. For this, the module has to pass the BIOS initialization for the PS2 port. In other words, the module has to respond to the protocol messages successfully so the BIOS identifies it as a working and valid keyboard. 

One problem you may have is the Bluetooth link being slow to connect on the first power on, so once the link is up it's too late because you went past BIOS posting. To solve this you can reset the system hot (not powering off) so the module will maintain the current BT link and have it ready as soon as the BIOS post comes. Another way of doing this, is using external power to power the board and connect the keyboard before turning on the system.

**Comment by mangemayur** [comment]
I have a very simple workaround :) .. as my device will not be connected to laptop directly but via USB C HUB which has power, HDMI and few USB hub ... and that gets initialized bit earlier -> also on restart the HUB remains powered on 

Thanks for the tip - thats exactly what i was missing about BIOS initilization, with what you just explained - i think i should be able to do it ... Once again Thanks :)

**Comment by acepe** [comment]
Hi @mangemayur.
if you're interested, I have ported the code from PS2 to USB for use with a ESP32-S3 (and possibly others with USB.-OTG support). https://github.com/acepe/esp32-bt2usb

**Comment by mangemayur** [comment]
Thanks:)

**Comment by Hamberthm** [comment]
I'm going to close this and permalink it on the readme. Feel free to keep discussing here/reopening as necessary.!
