### ISSUE TITLE
Does NVS works well?

### ISSUE THREAD

**Issue by username0occupied** [Hamberthm/esp32-bt2ps2#8]
I have tried your program, I found my esp32 could not relink my keyboard after rebooting.

**Comment by Hamberthm** [comment]
Hello there!

First of all, make sure line [line #119](https://github.com/Hamberthm/esp32-bt2ps2/blob/e4298b657bce084e72884f15ce24aac141fd48a8/main/main.cpp#L119) is commented out in the source, as is presented here. Just in case you have enabled that line by mistake.

NVS flash only takes a rol when using Bluetooth Classic keyboards with code entry pairing. Newer BLE keyboards don't need it, as the keyboard itself is responsible for reconnecting to the module.

In order to further assist you, I'll need more info and these questions precisely answered:

1. Is your keyboard BT Classic (code pairing) or BLE? (Exact brand and model will be perfect)
2. By "rebooting" do you mean powering on and off the host system, or the keyboard?
3. If talking about the host system, does the PS2 port power off and on? (Does it power-cycle the port?)
